<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Version>0.2.1</Version>
    <AssemblyVersion>0.2.1.0</AssemblyVersion>
    <FileVersion>0.2.1.0</FileVersion>
    <InformationalVersion>0.2.1-public-beta</InformationalVersion>
    <RepositoryUrl>https://github.com/Takayuki-Ishimaru/docredock</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
