// <auto-generated />
// WHATWG HTML named character references (2026-09-13), BSD-3-Clause.
// Source: https://html.spec.whatwg.org/entities.json
// Regenerate: python3 tools/generate-html-entities.py
// Copyright and license: THIRD-PARTY-NOTICES.txt
using System.Collections.Frozen;

namespace DocRedock.Markdown;

internal static partial class HtmlEntityTable
{
    internal static readonly FrozenDictionary<string, string> Names = Create();

    private static FrozenDictionary<string, string> Create()
    {
        var entries = new Dictionary<string, string>(2125, StringComparer.Ordinal);
        AddPart0(entries);
        AddPart1(entries);
        AddPart2(entries);
        return entries.ToFrozenDictionary(StringComparer.Ordinal);
    }
}
