#!/usr/bin/env python3
"""Generate the CommonMark semicolon-only HTML5 table; no third-party modules.
Run with --check to verify checked-in sources without modifying them.
Optionally use --input entities.json to regenerate from a downloaded snapshot.
"""
import argparse
import json
from pathlib import Path
from urllib.request import urlopen

URL = "https://html.spec.whatwg.org/entities.json"
HEADER = "// <auto-generated />\n// WHATWG HTML named character references (2026-09-13), BSD-3-Clause.\n// Source: https://html.spec.whatwg.org/entities.json\n// Regenerate: python3 tools/generate-html-entities.py\n// Copyright and license: THIRD-PARTY-NOTICES.txt\n"
ROOT = Path(__file__).resolve().parents[1]
MAIN = "// <auto-generated />\n// WHATWG HTML named character references (2026-09-13), BSD-3-Clause.\n// Source: https://html.spec.whatwg.org/entities.json\n// Regenerate: python3 tools/generate-html-entities.py\n// Copyright and license: THIRD-PARTY-NOTICES.txt\nusing System.Collections.Frozen;\n\nnamespace DocRedock.Markdown;\n\ninternal static partial class HtmlEntityTable\n{\n    internal static readonly FrozenDictionary<string, string> Names = Create();\n\n    private static FrozenDictionary<string, string> Create()\n    {\n        var entries = new Dictionary<string, string>(2125, StringComparer.Ordinal);\n        AddPart0(entries);\n        AddPart1(entries);\n        AddPart2(entries);\n        return entries.ToFrozenDictionary(StringComparer.Ordinal);\n    }\n}\n"

def generate(data):
    rows = [(name[1:-1], entry) for name, entry in sorted(data.items()) if name.endswith(";")]
    if len(data) != 2231 or len(rows) != 2125:
        raise ValueError("Upstream entity count changed; review the table and generator before updating.")
    result = {"HtmlEntityTable.g.cs": MAIN}
    for part in range(3):
        lines = []
        for name, entry in rows[part * 720:(part + 1) * 720]:
            points = entry["codepoints"]
            if not name.isascii() or not name.isalnum() or len(name) > 32:
                raise ValueError(f"Invalid entity name: {name}")
            if "".join(chr(point) for point in points) != entry["characters"]:
                raise ValueError(f"Inconsistent entity: {name}")
            value = "".join(("\\U%08x" if point > 0xffff else "\\u%04x") % point for point in points)
            lines.append(f'        entries.Add("{name}", "{value}");\n')
        result[f"HtmlEntityTable.Part{part}.g.cs"] = (
            HEADER + "namespace DocRedock.Markdown;\n\ninternal static partial class HtmlEntityTable\n{\n"
            + f"    private static void AddPart{part}(Dictionary<string, string> entries)\n"
            + "    {\n" + "".join(lines) + "    }\n}\n")
    return result

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.input:
        data = json.loads(args.input.read_text(encoding="utf-8"))
    else:
        with urlopen(URL, timeout=30) as response:
            data = json.load(response)
    for name, content in generate(data).items():
        path = ROOT / "src" / "DocRedock.Markdown" / name
        if args.check:
            if path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Generated table differs: {path}")
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    print("HTML5 table: 2125 semicolon-terminated names verified." if args.check else "HTML5 table generated.")

if __name__ == "__main__":
    main()
